### ISSUE TITLE
Dependency managers are pulling test files (porterstemmer_has_suffix.go)

### ISSUE THREAD

**Issue by bt** [blevesearch/go-porterstemmer#3]
Revisiting this @mschoch, relates to #1; `porterstemmer_has_suffix.go` is being built although it's a test file -- I've migrated to `vgo` and it's also pulling in v1.0.1 and so the fix hasn't been implemented yet.

Possible to bump the release tags so that `vgo` can pull the later version?

Thanks!

PS: For people also having the same issues in `vgo`, you can workaround this issue for the time being by adding the following to your `go.mod` file:

```
replace github.com/blevesearch/go-porterstemmer => github.com/blevesearch/go-porterstemmer master
```

**Comment by mschoch** [comment]
Release v1.0.2 should have fixed this issue.
